version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: ktech_zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: bitnami/kafka
    container_name: ktech_kafka
    ports:
      - "9094:9094"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "reddit-submissions:1:1, reddit-subreddit:1:1"
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_LOG_RETENTION_BYTES: 4073741824
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  spark-master:
    image: docker.io/bitnami/spark:3.3
    container_name: ktech_spark_master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"  # Spark Web UI
      - "7077:7077"
    depends_on:
      - kafka
    volumes:
      - ./:/app/ # Mount your Spark Streaming app
    restart: unless-stopped

  spark-worker:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8081:8081"

  hive-metastore:
    image: bde2020/hive
    container_name: ktech_hive_metastore
    environment:
      HIVE_DB: metastore
      POSTGRES_HOST: hive-metastore-postgresql
      POSTGRES_PORT: "5432"
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "9083:9083"
    command: /opt/hive/bin/start-metastore
    restart: unless-stopped
    depends_on:
      - hive-metastore-postgresql

  hive-server:
    image: bde2020/hive
    container_name: ktech_hive_server
    environment:
      HIVE_DB: metastore
      POSTGRES_HOST: hive-metastore-postgresql
      POSTGRES_PORT: "5432"
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "10000:10000"
    command: /opt/hive/bin/hive --service hiveserver2
    restart: unless-stopped
    depends_on:
      - hive-metastore

  hive-metastore-postgresql:
    image: postgres:12-alpine
    container_name: ktech_hive_metastore_postgresql
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init-hive
